"""Added UserDetail

Revision ID: 0cf93a492027
Revises: f461ece87f47
Create Date: 2017-01-20 09:30:12.016706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf93a492027'
down_revision = 'f461ece87f47'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('http_account', sa.String(length=1024), nullable=True),
    sa.Column('push_url', sa.String(length=2048), nullable=True),
    sa.Column('balance', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_details_user_id'), 'user_details', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_details_user_id'), table_name='user_details')
    op.drop_table('user_details')
    # ### end Alembic commands ###
