"""Added Country

Revision ID: 729f3b154547
Revises: 0cf93a492027
Create Date: 2017-01-20 09:33:32.815441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729f3b154547'
down_revision = '0cf93a492027'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.add_column('users', sa.Column('country_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_users_country_id'), 'users', ['country_id'], unique=False)
    op.create_foreign_key(None, 'users', 'countries', ['country_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_country_id'), table_name='users')
    op.drop_column('users', 'country_id')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
