"""Added more models

Revision ID: 8640c1dab484
Revises: c4188cb3d2ee
Create Date: 2017-01-10 13:09:47.123289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8640c1dab484'
down_revision = 'c4188cb3d2ee'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.add_column('movies', sa.Column('category_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_movies_category_id'), 'movies', ['category_id'], unique=False)
    op.create_foreign_key(None, 'movies', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.add_column('users', sa.Column('role', sa.SmallInteger(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('status', sa.SmallInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_index(op.f('ix_movies_category_id'), table_name='movies')
    op.drop_column('movies', 'category_id')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
