"""Demonstrate M2M relations

Revision ID: c2c01ebc8361
Revises: 729f3b154547
Create Date: 2017-02-03 09:32:29.859377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c01ebc8361'
down_revision = '729f3b154547'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_classes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_classes_name'), 'school_classes', ['name'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=True)
    op.create_table('student_school_classes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('school_class_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_school_classes_school_class_id'), 'student_school_classes', ['school_class_id'], unique=False)
    op.create_index(op.f('ix_student_school_classes_student_id'), 'student_school_classes', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_school_classes_student_id'), table_name='student_school_classes')
    op.drop_index(op.f('ix_student_school_classes_school_class_id'), table_name='student_school_classes')
    op.drop_table('student_school_classes')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_school_classes_name'), table_name='school_classes')
    op.drop_table('school_classes')
    # ### end Alembic commands ###
